# Generated by Django 3.2 on 2022-06-01 16:39

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='shop_item',
        ),
        migrations.AddField(
            model_name='list',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime.today, null=True),
        ),
        migrations.AddField(
            model_name='list',
            name='shop',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='list',
            name='shop_items',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='list',
            name='shopper',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
