# Generated by Django 3.2 on 2022-06-02 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0002_auto_20220601_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
